# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

language: scala

jdk:
  - openjdk6
  - oraclejdk8

env:
  - SCALA_VERSION=2.10.2
  - SCALA_VERSION=2.10.3
  - SCALA_VERSION=2.10.4
  - SCALA_VERSION=2.10.5
  - SCALA_VERSION=2.10.6
  - SCALA_VERSION=2.11.0
  - SCALA_VERSION=2.11.1
  - SCALA_VERSION=2.11.2
  - SCALA_VERSION=2.11.3
  - SCALA_VERSION=2.11.4
  - SCALA_VERSION=2.11.5
  - SCALA_VERSION=2.11.6
  - SCALA_VERSION=2.11.7
  - SCALA_VERSION=2.11.8
  - SCALA_VERSION=2.11.11
  - SCALA_VERSION=2.12.0
  - SCALA_VERSION=2.12.1
  - SCALA_VERSION=2.12.2
  - SCALA_VERSION=2.12.3
  - SCALA_VERSION=2.13.0-M2

# there's no better way it seems.. https://github.com/travis-ci/travis-ci/issues/1519
matrix:
  exclude:
    # scala 2.12.x requires jdk8
    - jdk: openjdk6
      env: SCALA_VERSION=2.12.0
    - jdk: openjdk6
      env: SCALA_VERSION=2.12.1
    - jdk: openjdk6
      env: SCALA_VERSION=2.12.2
    - jdk: openjdk6
      env: SCALA_VERSION=2.12.3
    - jdk: openjdk6
      env: SCALA_VERSION=2.13.0-M2

# Increasing ReservedCodeCacheSize minimizes scala compiler-interface compile times
script:
  - sbt -J-XX:ReservedCodeCacheSize=256M ++$SCALA_VERSION test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
